feat: add delete method and add validation of update id before update

diff --git a/scripts/functions-task b/scripts/functions-task
--- a/scripts/functions-task
+++ b/scripts/functions-task
@@ -23,45 +23,64 @@ createTask() {
 }
 
 updateTask() {
-  if [[ -n "$2" && -z "$3" ]]; then
-    jq --argjson id "$1" --arg status "$2" \
-      '(.[] | select(.id == $id) | .status) = $status' \
-      "$FILE_JSON" >temp.json && mv temp.json "$FILE_JSON"
+  data=$(jq --argjson id "$1" '.[] | select(.id == $id)' "$FILE_JSON")
+  if [[ -n $data ]]; then
 
-  elif [[ -z "$2" && -n "$3" ]]; then
-    jq --argjson id "$1" --arg description "$3" \
-      '(.[] | select(.id == $id) | .description) = $description' \
-      "$FILE_JSON" >temp.json && mv temp.json "$FILE_JSON"
+    if [[ -n "$2" && -z "$3" ]]; then
+      jq --argjson id "$1" --arg status "$2" \
+        '(.[] | select(.id == $id) | .status) = $status' \
+        "$FILE_JSON" >temp.json && mv temp.json "$FILE_JSON"
 
-  elif [[ -n "$2" && -n "$3" ]]; then
-    jq --argjson id "$1" \
-      --arg status "$2" \
-      --arg description "$3" \
-      '(.[] | select(.id == $id)) |= (.status = $status | .description = $description)' \
-      "$FILE_JSON" >temp.json && mv temp.json "$FILE_JSON"
+    elif [[ -z "$2" && -n "$3" ]]; then
+      jq --argjson id "$1" --arg description "$3" \
+        '(.[] | select(.id == $id) | .description) = $description' \
+        "$FILE_JSON" >temp.json && mv temp.json "$FILE_JSON"
+
+    elif [[ -n "$2" && -n "$3" ]]; then
+      jq --argjson id "$1" \
+        --arg status "$2" \
+        --arg description "$3" \
+        '(.[] | select(.id == $id)) |= (.status = $status | .description = $description)' \
+        "$FILE_JSON" >temp.json && mv temp.json "$FILE_JSON"
+    else
+      echo "No valid parameters provided for update."
+      exit 1
+    fi
+
+    taskUpdated=$(jq ".[] | select(.id == $1)" $FILE_JSON)
+
+    echo "Task updated successfully:"
+    echo ""
+    printf "| %-3s | %-50s | %-13s | %-19s | %-19s |\n" "ID" "Description" "Status" "Created At" "Updated At"
+    printf "| %-3s | %-50s | %-13s | %-19s | %-19s |\n" "---" "--------------------------------------------------" "-------------" "-------------------" "-------------------"
+
+    id=$(echo $taskUpdated | jq ".id")
+    description=$(echo $taskUpdated | jq ".description")
+    status=$(echo $taskUpdated | jq ".status")
+    createdAt=$(echo $taskUpdated | jq ".createdAt")
+    updateAt=$(echo $taskUpdated | jq ".updateAt")
+
+    createdAt=$(convertDateUnixToYMDHMS $createdAt)
+    updateAt=$(convertDateUnixToYMDHMS $updateAt)
+
+    printf "| %-3s | %-50s | %-13s | %-19s | %-19s |\n" "$id" "$description" "$status" "$createdAt" "$updateAt"
+    printf "| %-3s | %-50s | %-13s | %-19s | %-19s |\n" "---" "--------------------------------------------------" "-------------" "-------------------" "-------------------"
+    echo ""
   else
-    echo "No valid parameters provided for update."
+    echo "Error: Id task not fount: $1."
     exit 1
   fi
+}
 
-  taskUpdated=$(jq ".[] | select(.id == $1)" $FILE_JSON)
-
-  echo ""
-  printf "| %-3s | %-50s | %-13s | %-19s | %-19s |\n" "ID" "Description" "Status" "Created At" "Updated At"
-  printf "| %-3s | %-50s | %-13s | %-19s | %-19s |\n" "---" "--------------------------------------------------" "-------------" "-------------------" "-------------------"
-
-  id=$(echo $taskUpdated | jq ".id")
-  description=$(echo $taskUpdated | jq ".description")
-  status=$(echo $taskUpdated | jq ".status")
-  createdAt=$(echo $taskUpdated | jq ".createdAt")
-  updateAt=$(echo $taskUpdated | jq ".updateAt")
-
-  createdAt=$(convertDateUnixToYMDHMS $createdAt)
-  updateAt=$(convertDateUnixToYMDHMS $updateAt)
-
-  printf "| %-3s | %-50s | %-13s | %-19s | %-19s |\n" "$id" "$description" "$status" "$createdAt" "$updateAt"
-  printf "| %-3s | %-50s | %-13s | %-19s | %-19s |\n" "---" "--------------------------------------------------" "-------------" "-------------------" "-------------------"
-  echo ""
+deleteTask() {
+  data=$(jq --argjson id "$1" '.[] | select(.id == $id)' "$FILE_JSON")
+  if [[ -n $data ]]; then
+    jq --argjson id "$1" 'map(select(.id != $id))' "$FILE_JSON" >temp.json && mv temp.json "$FILE_JSON"
+    echo "Task delete successfully: $1"
+  else
+    echo "Error: Id task not fount: $1."
+    exit 1
+  fi
 }
 
 getAllTasks() {
